new testing framework

diff --git a/tests/recipes/03_sign_der b/tests/recipes/03_sign_der
--- a/tests/recipes/03_sign_der
+++ b/tests/recipes/03_sign_der
@@ -1,76 +1,54 @@
 #!/bin/sh
-# Sign a PE/CAB/MSI file with the encrypted private key file in the DER format.
+# Sign a file with an encrypted private key in the DER format.
 # Requires OpenSSL 1.0.0 or later
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=3
 
-# PE file
-test_name="031. Sign a PE file with the encrypted private key file in the DER format"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
-        -pass passme \
-        -in "test.exe" -out "test_031.exe"
-    verify_signature "$?" "031" "exe" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") filetype=CAT; format_nr=1 ;;
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
 
-# CAB file
-test_name="032. Sign a CAB file with the encrypted private key file in the DER format"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
-        -pass passme \
-        -in "test.ex_" -out "test_032.ex_"
-    verify_signature "$?" "032" "ex_" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    number="$test_nr$format_nr"
+    test_name="Sign a $filetype$desc file with an encrypted private key in the DER format"
+    printf "\n%03d. %s\n" "$number" "$test_name"
 
-# MSI file
-test_name="033. Sign a MSI file with the encrypted private key file in the DER format"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
-        -pass passme \
-        -in "sample.msi" -out "test_033.msi"
-    verify_signature "$?" "033" "msi" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -st "1556668800" \
+      -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
+      -pass passme \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    result=$?
 
-# CAT file
-test_name="034. Sign a CAT file with the encrypted private key file in the DER format"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
-        -pass passme \
-        -in "good.cat" -out "test_034.cat"
-    verify_signature "$?" "034" "cat" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "sha256sum" "osslsigncode" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/07_sign_timestamp b/tests/recipes/07_sign_timestamp
--- a/tests/recipes/07_sign_timestamp
+++ b/tests/recipes/07_sign_timestamp
@@ -1,83 +1,61 @@
 #!/bin/sh
-# Sign a PE/CAB/MSI file with Authenticode timestamping
+# Sign a file with Authenticode timestamping
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=7
 
-# PE file
-test_name="071. Sign a PE file with Authenticode timestamping"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe" && ! grep -q "no libcurl available" "results.log"
-  then
-    ../../osslsigncode sign -h sha256 \
+if ! grep -q "no libcurl available" "results.log"; then
+  for file in ${script_path}/../logs/notsigned/*.*
+    do
+      name="${file##*/}"
+      ext="${file##*.}"
+      desc=""
+      case $ext in
+        "cat") filetype=CAT; format_nr=1 ;;
+        "msi") filetype=MSI; format_nr=2 ;;
+        "ex_") filetype=CAB; format_nr=3 ;;
+        "exe") filetype=PE; format_nr=4 ;;
+        "ps1")
+          filetype=TXT
+          if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+            format_nr=5
+            desc=" UTF-16LE(BOM)"
+          elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+            format_nr=6
+            desc=" UTF-8(BOM)"
+        else
+            format_nr=7
+            desc=" UTF-8"
+          fi ;;
+      esac
+
+      number="$test_nr$format_nr"
+      test_name="Sign a $filetype$desc file with Authenticode timestamping"
+      printf "\n%03d. %s\n" "$number" "$test_name"
+
+      ../../osslsigncode sign -h sha256 \
         -st "1556668800" \
         -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
         -t http://time.certum.pl/ \
         -t http://timestamp.digicert.com/ \
-        -verbose \
-        -in "test.exe" -out "test_071.exe" 2>> "results.log" 1>&2
-    verify_signature "$?" "071" "exe" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "Timestamp Server Signature" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+        -in "notsigned/$name" -out "test_$number.$ext"
+      result=$?
 
-# CAB file
-test_name="072. Sign a CAB file with Authenticode timestamping"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_" && ! grep -q "no libcurl available" "results.log"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -t http://time.certum.pl/ \
-        -t http://timestamp.digicert.com/ \
-        -verbose \
-        -in "test.ex_" -out "test_072.ex_" 2>> "results.log" 1>&2
-    verify_signature "$?" "072" "ex_" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "Timestamp Server Signature" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
+      if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+        printf "%s\n" "Compare file prefix failed"
+        test_result "1" "$number" "$test_name"
+      else
+        verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+          "UNUSED_PATTERN" "osslsigncode" "UNUSED_PATTERN"
+        test_result "$?" "$number" "$test_name"
+      fi
+    done
   else
-    printf "Test skipped\n"
-  fi
-
-# MSI file
-test_name="073. Sign a MSI file with Authenticode timestamping"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi" && ! grep -q "no libcurl available" "results.log"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -t http://time.certum.pl/ \
-        -t http://timestamp.digicert.com/ \
-        -verbose \
-        -in "sample.msi" -out "test_073.msi"
-    verify_signature "$?" "073" "msi" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "Timestamp Server Signature" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
-
-# CAT file
-test_name="074. Sign a CAT file with Authenticode timestamping"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat" && ! grep -q "no libcurl available" "results.log"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -t http://time.certum.pl/ \
-        -t http://timestamp.digicert.com/ \
-        -verbose \
-        -in "good.cat" -out "test_074.cat"
-    verify_signature "$?" "074" "cat" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "Timestamp Server Signature" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
+    format_nr=0
+    number="$test_nr$format_nr"
+    test_name="Sign a file with Authenticode timestamping"
+    printf "\n%03d. %s\nTest skipped\n" "$number" "$test_name"
   fi
 
 exit 0
diff --git a/tests/recipes/12_sign_readpass_pem b/tests/recipes/12_sign_readpass_pem
--- a/tests/recipes/12_sign_readpass_pem
+++ b/tests/recipes/12_sign_readpass_pem
@@ -1,75 +1,54 @@
 #!/bin/sh
-# Sign a PE/CAB/MSI file with a PEM key file and a password read from password.txt file.
+# Sign a file with a PEM key and a password read from password.txt file.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=12
 
-# PE file
-test_name="121. Sign a PE file with the PEM key file and the file with a password"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -readpass "${script_path}/../certs/password.txt" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.exe" -out "test_121.exe"
-    verify_signature "$?" "121" "exe" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") filetype=CAT; format_nr=1 ;;
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
 
-# CAB file
-test_name="122. Sign a CAB file with a PEM key file and the file with a password"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -readpass "${script_path}/../certs/password.txt" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/keyp.pem" \
-        -in "test.ex_" -out "test_122.ex_"
-    verify_signature "$?" "122" "ex_" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    number="$test_nr$format_nr"
+    test_name="Sign a $filetype$desc file with a PEM key and a password read from password.txt file"
+    printf "\n%03d. %s\n" "$number" "$test_name"
 
-# MSI file
-test_name="123. Sign a MSI file with a PEM key file and the file with a password"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -readpass "${script_path}/../certs/password.txt" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/keyp.pem" \
-        -in "sample.msi" -out "test_123.msi"
-    verify_signature "$?" "123" "msi" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -st "1556668800" \
+      -addUnauthenticatedBlob \
+      -readpass "${script_path}/../certs/password.txt" \
+      -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/keyp.pem" \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    result=$?
 
-# CAT file
-test_name="124. Sign a CAT file with a PEM key file and the file with a password"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -readpass "${script_path}/../certs/password.txt" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/keyp.pem" \
-        -in "good.cat" -out "test_124.cat"
-    verify_signature "$?" "124" "cat" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "UNUSED_PATTERN" "osslsigncode" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/13_sign_readpass_pkcs12 b/tests/recipes/13_sign_readpass_pkcs12
--- a/tests/recipes/13_sign_readpass_pkcs12
+++ b/tests/recipes/13_sign_readpass_pkcs12
@@ -1,76 +1,54 @@
 #!/bin/sh
-# Sign a PE/CAB/MSI file with the certificate and key stored in a PKCS#12 container
+# Sign a file with the certificate and key stored in a PKCS#12 container
 # and a password read from password.txt file.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=13
 
-# PE file
-test_name="131. Sign a PE file with a PKCS#12 container and the file with a password"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -readpass "${script_path}/../certs/password.txt" \
-        -pkcs12 "${script_path}/../certs/cert.p12" \
-        -in "test.exe" -out "test_131.exe"
-    verify_signature "$?" "131" "exe" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") filetype=CAT; format_nr=1 ;;
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
 
-# CAB file
-test_name="132. Sign a CAB file with a PKCS#12 container and the file with a password"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -readpass "${script_path}/../certs/password.txt" \
-        -pkcs12 "${script_path}/../certs/cert.p12" \
-        -in "test.ex_" -out "test_132.ex_"
-    verify_signature "$?" "132" "ex_" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    number="$test_nr$format_nr"
+    test_name="Sign a $filetype$desc file with a PKCS#12 container and the file with a password"
+    printf "\n%03d. %s\n" "$number" "$test_name"
 
-# MSI file
-test_name="133. Sign a MSI file with a PKCS#12 container and the file with a password"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -readpass "${script_path}/../certs/password.txt" \
-        -pkcs12 "${script_path}/../certs/cert.p12" \
-        -in "sample.msi" -out "test_133.msi"
-    verify_signature "$?" "133" "msi" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -st "1556668800" \
+      -readpass "${script_path}/../certs/password.txt" \
+      -pkcs12 "${script_path}/../certs/cert.p12" \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    result=$?
 
-# CAT file
-test_name="134. Sign a CAT file with a PKCS#12 container and the file with a password"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -readpass "${script_path}/../certs/password.txt" \
-        -pkcs12 "${script_path}/../certs/cert.p12" \
-        -in "good.cat" -out "test_134.cat"
-    verify_signature "$?" "134" "cat" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "UNUSED_PATTERN" "osslsigncode" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/17_sign_crosscertfile b/tests/recipes/17_sign_crosscertfile
--- a/tests/recipes/17_sign_crosscertfile
+++ b/tests/recipes/17_sign_crosscertfile
@@ -1,77 +1,55 @@
 #!/bin/sh
-# Add an additional certificate to the signature block of the PE/CAB/MSI file.
+# Add an additional certificate to the signature block of the file.
 # https://docs.microsoft.com/en-us/windows-hardware/drivers/install/authenticode-signing-of-csps
 # https://docs.microsoft.com/en-us/windows/win32/seccertenroll/about-cross-certification
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=17
 
-# PE file
-test_name="171. Add an additional certificate to the signature block of the PE file"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -ac "${script_path}/../certs/crosscert.pem" \
-        -in "test.exe" -out "test_171.exe"
-    verify_signature "$?" "171" "exe" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "crosscert" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") filetype=CAT; format_nr=1 ;;
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
 
-# CAB file
-test_name="172. Add an additional certificate to the signature block of the CAB file"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -ac "${script_path}/../certs/crosscert.pem" \
-        -in "test.ex_" -out "test_172.ex_"
-    verify_signature "$?" "172" "ex_" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "crosscert" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    number="$test_nr$format_nr"
+    test_name="Add an additional certificate to the signature block of a $filetype$desc file"
+    printf "\n%03d. %s\n" "$number" "$test_name"
 
-# MSI file
-test_name="173. Add an additional certificate to the signature block of the MSI file"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -ac "${script_path}/../certs/crosscert.pem" \
-        -in "sample.msi" -out "test_173.msi"
-    verify_signature "$?" "173" "msi" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "crosscert" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -st "1556668800" \
+      -ac "${script_path}/../certs/crosscert.pem" \
+      -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    result=$?
 
-# CAT file
-test_name="174. Add an additional certificate to the signature block of the CAT file"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -ac "${script_path}/../certs/crosscert.pem" \
-        -in "good.cat" -out "test_174.cat"
-    verify_signature "$?" "174" "cat" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "crosscert" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "UNUSED_PATTERN" "crosscert" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/22_sign_hash_sha1 b/tests/recipes/22_sign_hash_sha1
--- a/tests/recipes/22_sign_hash_sha1
+++ b/tests/recipes/22_sign_hash_sha1
@@ -1,29 +1,52 @@
 #!/bin/sh
-# Sign a PE file with SHA1 set of cryptographic hash functions.
+# Sign a file with SHA1 set of cryptographic hash functions.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=22
 
-# PE file
-test_name="221. Sign a PE file with SHA1 set of cryptographic hash functions"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") filetype=CAT; format_nr=1 ;;
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
+
+    number="$test_nr$format_nr"
+    test_name="Sign a $filetype$desc file with SHA1 set of cryptographic hash functions"
+    printf "\n%03d. %s\n" "$number" "$test_name"
+
     ../../osslsigncode sign -h sha1 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.exe" -out "test_221.exe"
-    verify_signature "$?" "221" "exe" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "SHA1" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -st "1556668800" \
+      -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    result=$?
 
-# CAB file
-
-# MSI file
-
-# CAT file
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "UNUSED_PATTERN" "SHA1" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/35_remove_signature b/tests/recipes/35_remove_signature
--- a/tests/recipes/35_remove_signature
+++ b/tests/recipes/35_remove_signature
@@ -1,64 +1,54 @@
 #!/bin/sh
-# Remove the signature from the PE/CAB/MSI file.
+# Remove the signature from the file.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=35
 
-# PE file
-test_name="351. Remove the signature from the PE file"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") continue;; # Unsupported command
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
+
+    number="$test_nr$format_nr"
+    test_name="Remove the signature from the $filetype$desc file"
+    printf "\n%03d. %s\n" "$number" "$test_name"
+
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.exe" -out "test_351_signed.exe" && \
+      -st "1556668800" \
+      -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
+      -in "notsigned/$name" -out "signed_$number.$ext"
     ../../osslsigncode remove-signature \
-        -in "test_351_signed.exe" -out "test_351.exe"
-    verify_signature "$?" "351" "exe" "fail" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -in "signed_$number.$ext" -out "test_$number.$ext"
+    result=$?
 
-# CAB file
-test_name="352. Remove the signature from the CAB file"
-printf "\n%s\n" "$test_name"
-if [ -s "test.ex_" ]
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.ex_" -out "test_352_signed.ex_" && \
-    ../../osslsigncode remove-signature \
-        -in "test_352_signed.ex_" -out "test_352.ex_"
-    verify_signature "$?" "352" "ex_" "fail" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
-
-# MSI file
-test_name="353. Remove the signature from the MSI file"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "sample.msi" -out "test_353_signed.msi" && \
-    ../../osslsigncode remove-signature \
-        -in "test_353_signed.msi" -out "test_353.msi"
-    verify_signature "$?" "353" "msi" "fail" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
-
-# CAT file
-# Unsupported command
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "fail" "@2019-09-01 12:00:00" \
+        "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/39_add_signature_blob b/tests/recipes/39_add_signature_blob
--- a/tests/recipes/39_add_signature_blob
+++ b/tests/recipes/39_add_signature_blob
@@ -1,84 +1,55 @@
 #!/bin/sh
-# Add an unauthenticated blob to the PE/CAB/MSI file.
+# Add an unauthenticated blob to the signed file.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=39
 
-# PE file
-test_name="391. Add an unauthenticated blob to the PE file"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.exe" -out "test_391_signed.exe"
-    ../../osslsigncode add \
-        -addUnauthenticatedBlob \
-        -in "test_391_signed.exe" -out "test_391.exe"
-    verify_signature "$?" "391" "exe" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "BEGIN_BLOB" "MODIFY"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") filetype=CAT; format_nr=1 ;;
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
 
-# CAB file
-test_name="392. Add an unauthenticated blob to the CAB file"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.ex_" -out "test_392_signed.ex_"
-    ../../osslsigncode add \
-        -addUnauthenticatedBlob \
-        -in "test_392_signed.ex_" -out "test_392.ex_"
-    verify_signature "$?" "392" "ex_" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "BEGIN_BLOB" "MODIFY"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    number="$test_nr$format_nr"
+    test_name="Add an unauthenticated blob to the $filetype$desc signed file"
+    printf "\n%03d. %s\n" "$number" "$test_name"
 
-# MSI file
-test_name="393. Add an unauthenticated blob to the MSI file"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "sample.msi" -out "test_393_signed.msi"
+      -st "1556668800" \
+      -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
+      -in "notsigned/$name" -out "signed_$number.$ext"
     ../../osslsigncode add \
-        -addUnauthenticatedBlob \
-        -in "test_393_signed.msi" -out "test_393.msi"
-    verify_signature "$?" "393" "msi" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "BEGIN_BLOB" "MODIFY"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -addUnauthenticatedBlob \
+      -in "signed_$number.$ext" -out "test_$number.$ext"
+    result=$?
 
-# CAT file
-# The message digest is checked by PKCS7_verify()
-test_name="394. Add an unauthenticated blob to the CAT file"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "good.cat" -out "test_394_signed.cat"
-    ../../osslsigncode add \
-        -addUnauthenticatedBlob \
-        -in "test_394_signed.cat" -out "test_394.cat"
-    verify_signature "$?" "394" "cat" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "UNUSED_PATTERN" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "UNUSED_PATTERN" "Unauthenticated Data Blob" "MODIFY"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/53_verify_rfc3161 b/tests/recipes/53_verify_rfc3161
--- a/tests/recipes/53_verify_rfc3161
+++ b/tests/recipes/53_verify_rfc3161
@@ -1,86 +1,62 @@
 #!/bin/sh
-# Verify PE/CAB/MSI file signature with RFC3161 timestamping after the cert has been expired.
+# Verify a file signed with RFC3161 timestamping after the cert has been expired.
 
 . $(dirname $0)/../test_library
+script_path=$(pwd)
+test_nr=53
 
-# PE file
-test_name="531. Verify PE file signature with RFC3161 after the cert has been expired"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe" && ! grep -q "no libcurl available" "results.log"
-  then
-    TZ=GMT faketime -f '@2019-05-01 00:00:00' /bin/bash -c '
-        script_path=$(pwd)
-        ../../osslsigncode sign -h sha256 \
-            -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-            -ts http://time.certum.pl/ \
-            -ts http://timestamp.digicert.com/ \
-            -verbose \
-            -in "test.exe" -out "test_531.exe" 2>> "results.log" 1>&2'
-    verify_signature "$?" "531" "exe" "success" "@2025-01-01 12:00:00" \
-	"UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+if ! grep -q "no libcurl available" "results.log"; then
+  for file in ${script_path}/../logs/notsigned/*.*
+    do
+      name="${file##*/}"
+      ext="${file##*.}"
+      desc=""
+      case $ext in
+        "cat") filetype=CAT; format_nr=1 ;;
+        "msi") filetype=MSI; format_nr=2 ;;
+        "ex_") filetype=CAB; format_nr=3 ;;
+        "exe") filetype=PE; format_nr=4 ;;
+        "ps1")
+          filetype=TXT
+          if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+            format_nr=5
+            desc=" UTF-16LE(BOM)"
+          elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+            format_nr=6
+            desc=" UTF-8(BOM)"
+          else
+            format_nr=7
+            desc=" UTF-8"
+          fi ;;
+      esac
 
-# CAB file
-test_name="532. Verify CAB file signature with RFC3161 after the cert has been expired"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_" && ! grep -q "no libcurl available" "results.log"
-  then
-    TZ=GMT faketime -f '@2019-05-01 00:00:00' /bin/bash -c '
-        script_path=$(pwd)
-        ../../osslsigncode sign -h sha256 \
-            -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-            -ts http://time.certum.pl/ \
-            -ts http://timestamp.digicert.com/ \
-            -verbose \
-            -in "test.ex_" -out "test_532.ex_" 2>> "results.log" 1>&2'
-    verify_signature "$?" "532" "ex_" "success" "@2025-01-01 12:00:00" \
-	"UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      number="$test_nr$format_nr"
+      test_name="Verify a $filetype$desc file signed with RFC3161 after the cert has been expired"
+      printf "\n%03d. %s\n" "$number" "$test_name"
 
-# MSI file
-test_name="533. Verify MSI file signature with RFC3161 after the cert has been expired"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi" && ! grep -q "no libcurl available" "results.log"
-  then
-    TZ=GMT faketime -f '@2019-05-01 00:00:00' /bin/bash -c '
-        script_path=$(pwd)
-        ../../osslsigncode sign -h sha256 \
-            -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-            -ts http://time.certum.pl/ \
-            -ts http://timestamp.digicert.com/ \
-            -verbose \
-            -in "sample.msi" -out "test_533.msi"'
-    verify_signature "$?" "533" "msi" "success" "@2025-01-01 12:00:00" \
-	"UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      ../../osslsigncode sign -h sha256 \
+        -st "1556668800" \
+        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
+        -ts http://time.certum.pl/ \
+        -ts http://timestamp.digicert.com/ \
+        -verbose \
+        -in "notsigned/$name" -out "test_$number.$ext"
+      result=$?
 
-# CAT file
-test_name="534. Verify CAT file signature with RFC3161 after the cert has been expired"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat" && ! grep -q "no libcurl available" "results.log"
-  then
-    TZ=GMT faketime -f '@2019-05-01 00:00:00' /bin/bash -c '
-        script_path=$(pwd)
-        ../../osslsigncode sign -h sha256 \
-            -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-            -ts http://time.certum.pl/ \
-            -ts http://timestamp.digicert.com/ \
-            -verbose \
-            -in "good.cat" -out "test_534.cat"'
-    verify_signature "$?" "534" "cat" "success" "@2025-01-01 12:00:00" \
-	"UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
+      if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+        printf "%s\n" "Compare file prefix failed"
+        test_result "1" "$number" "$test_name"
+      else
+        verify_signature "$result" "$number" "$ext" "success" "@2025-01-01 12:00:00" \
+          "UNUSED_PATTERN" "UNUSED_PATTERN" "UNUSED_PATTERN"
+        test_result "$?" "$number" "$test_name"
+      fi
+    done
   else
-    printf "Test skipped\n"
+    format_nr=0
+    number="$test_nr$format_nr"
+    test_name="Verify a file signed with RFC3161 after the cert has been expired"
+    printf "\n%03d. %s\nTest skipped\n" "$number" "$test_name"
   fi
 
 exit 0
diff --git a/tests/test_library b/tests/test_library
--- a/tests/test_library
+++ b/tests/test_library
@@ -7,7 +7,8 @@ cd "${result_path}"
 
 test_result() {
 #1 last exit status
-#2 test name
+#2 test number
+#3 test name
 
   local result=0
 
@@ -16,7 +17,7 @@ test_result() {
       printf "%s\n" "Test succeeded"
     else
       printf "%s\n" "Test failed"
-      printf "%-80s\t%s\n" "$2" "failed" 1>&3
+      printf "%03d. %-90s\t%s\n" "$2" "$3" "failed" 1>&3
       result=1
     fi
   return "$result"
@@ -32,21 +33,24 @@ modify_blob() {
   initial_blob=$(echo -n "$3" | xxd -p)
   modified_blob=$(echo -n "FAKE" | xxd -p)
   zero_blob="00000000"
+
   xxd -p -c 1000 "test_$1.$2" | \
       sed "s/$initial_blob$zero_blob/$initial_blob$modified_blob/" | \
-      xxd -p -r > "test_$1_changed.$2"
+      xxd -p -r > "changed_$1.$2"
+
   ../../osslsigncode verify \
       -CAfile "${script_path}/../certs/CACert.pem" \
       -CRLfile "${script_path}/../certs/CACertCRL.pem" \
-      -in "test_$1_changed.$2" 2>> "verify.log" 1>&2
+      -in "changed_$1.$2" 2>> "verify.log" 1>&2
   result=$?
+
   if test "$result" -ne 0 \
-      -o $(grep -e "Calculated DigitalSignature" -e "Calculated message digest" "verify.log" | uniq | wc -l) -ne 1
+      -o $(grep -e "Calculated DigitalSignature" -e "Calculated message digest" "verify.log" | uniq | wc -l) -gt 1
     then
       printf "Failed: verify error or non-unique message digests found\n" 2>> "verify.log" 1>&2
       result=1
     else
-      rm -f "test_$1_changed.$2"
+      rm -f "changed_$1.$2"
     fi
 
   return "$result"
@@ -55,29 +59,19 @@ modify_blob() {
 search_pattern() {
 # $1 test number
 # $2 filename extension
-# $3 ASCII or HEX "$7 pattern" format
-# $4 pattern searched in a binary file or verify.log
-# $5 modify requirement
+# $3 pattern searched in a binary file or verify.log
 
   local result=0
 
-  if test "$3" = "ASCII"
+  if ! grep -q "$3" "verify.log"
     then
-      hex_pattern=$(echo -n "$4" | xxd -p)
-    else
-      hex_pattern=$4
+      hex_pattern=$(echo -n "$3" | xxd -p)
+      if ! xxd -p -c 1000 "test_$1.$2" | grep "$hex_pattern" 2>> /dev/null 1>&2
+        then
+          result=1
+          printf "Failed: $3 not found\n"
+        fi
     fi
-  if ! grep -q "$4" "verify.log" && \
-      ! xxd -p -c 1000 "test_$1.$2" | grep "$hex_pattern" 2>> /dev/null 1>&2
-    then
-      result=1
-      printf "Failed: $4 not found\n"
-    elif test "$5" = "MODIFY"
-      then
-        modify_blob "$1" "$2" "$4"
-        result=$?
-      fi
-
   return "$result"
 }
 
@@ -88,11 +82,11 @@ verify_signature() {
 # $4 expected result
 # $5 fake time
 # $6 sha256sum requirement
-# $7 ASCII or HEX "$7 pattern" format
-# $8 pattern searched in a binary file or verify.log
-# $9 modify requirement
+# $7 pattern searched in the verify.log file
+# $8 modify requirement
 
   local result=0
+
   printf "" > "verify.log"
   if test "$1" -eq 0
     then
@@ -106,23 +100,31 @@ verify_signature() {
               -in "test_tmp.tmp" 2>> "verify.log" 1>&2'
       result=$?
       rm -f "test_tmp.tmp"
-      if test "$result" -eq 0 -a "$7" != "UNUSED_PATTERN" -a "$8" != "UNUSED_PATTERN"
+
+      if test "$result" -eq 0 -a "$7" != "UNUSED_PATTERN"
         then
-          search_pattern "$2" "$3" "$7" "$8" "$9"
+          search_pattern "$2" "$3" "$7"
           result=$?
         fi
+
+      if test "$result" -eq 0 -a "$8" == "MODIFY"
+        then
+          modify_blob "$2" "$3" "$7"
+          result=$?
+       fi
+
       if test "$6" = "sha256sum"
         then
-          sha256sum "test_$2.$3" 2>> "sha256sum_$3.log" 1>&2
+          sha256sum "test_$2.$3" 2>> "sha256sum/$3.log" 1>&2
         fi
+
       if test "$4" = "success" -a "$result" -eq 0
         then
-          rm -f "test_$2.$3" "test_$2_signed.$3" "test_$2_modifed.$3" "test_$2_changed.$3"
-          rm -f "test_$2_a.$3" "test_$2_b.$3"
-          result=0
+          rm -f "test_$2.$3" "signed_$2.$3" "signed1_$2.$3" "signed2_$2.$3"
         elif test "$4" = "fail" -a "$result" -eq 1
           then
-            rm -f "test_$2.$3" "test_$2_signed.$3" "test_$2_modifed.$3" "test_$2_changed.$3"
+            rm -f "test_$2.$3" "signed_$2.$3" "signed1_$2.$3" "signed2_$2.$3"
+            rm -f "changed_$2.$3"
             cat "verify.log" >> "results.log"
             result=0
         else
