new testing framework

diff --git a/tests/recipes/04_sign_spc_pvk b/tests/recipes/04_sign_spc_pvk
--- a/tests/recipes/04_sign_spc_pvk
+++ b/tests/recipes/04_sign_spc_pvk
@@ -1,76 +1,54 @@
 #!/bin/sh
-# Sign a PE/CAB/MSI file with the certificate file in the SPC format
-# and the private key file in the Microsoft Private Key (PVK) format.
+# Sign a file with a certificate in the SPC format
+# and a private key in the Microsoft Private Key (PVK) format.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=4
 
-# PE file
-test_name="041. Sign a PE file a SPC certificate file and a PVK private key file"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -spc "${script_path}/../certs/cert.spc" -key "${script_path}/../certs/key.pvk" \
-        -pass passme \
-        -in "test.exe" -out "test_041.exe"
-    verify_signature "$?" "041" "exe" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") filetype=CAT; format_nr=1 ;;
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
 
-# CAB file
-test_name="042. Sign a CAB file a SPC certificate file and a PVK private key file"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -spc "${script_path}/../certs/cert.spc" -key "${script_path}/../certs/key.pvk" \
-        -pass passme \
-        -in "test.ex_" -out "test_042.ex_"
-    verify_signature "$?" "042" "ex_" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    number="$test_nr$format_nr"
+    test_name="Sign a $filetype$desc file with a SPC certificate and a PVK private key"
+    printf "\n%03d. %s\n" "$number" "$test_name"
 
-# MSI file
-test_name="043. Sign a MSI file a SPC certificate file and a PVK private key file"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -spc "${script_path}/../certs/cert.spc" -key "${script_path}/../certs/key.pvk" \
-        -pass passme \
-        -in "sample.msi" -out "test_043.msi"
-    verify_signature "$?" "043" "msi" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -st "1556668800" \
+      -spc "${script_path}/../certs/cert.spc" -key "${script_path}/../certs/key.pvk" \
+      -pass passme \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    result=$?
 
-# CAT file
-test_name="044. Sign a CAT file a SPC certificate file and a PVK private key file"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -spc "${script_path}/../certs/cert.spc" -key "${script_path}/../certs/key.pvk" \
-        -pass passme \
-        -in "good.cat" -out "test_044.cat"
-    verify_signature "$?" "044" "cat" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "sha256sum" "osslsigncode" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/05_sign_pkcs12 b/tests/recipes/05_sign_pkcs12
--- a/tests/recipes/05_sign_pkcs12
+++ b/tests/recipes/05_sign_pkcs12
@@ -1,74 +1,53 @@
 #!/bin/sh
-# Sign a PE/CAB/MSI file with the certificate and key stored in a PKCS#12 container.
+# Sign a file with a certificate and a key stored in a PKCS#12 container.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=5
 
-# PE file
-test_name="051. Sign a PE file with a certificate and key stored in a PKCS#12 container"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -pkcs12 "${script_path}/../certs/cert.p12" -pass passme \
-        -in "test.exe" -out "test_051.exe"
-    verify_signature "$?" "051" "exe" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") filetype=CAT; format_nr=1 ;;
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
 
-# CAB file
-test_name="052. Sign a CAB file with a certificate and key stored in a PKCS#12 container"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -pkcs12 "${script_path}/../certs/cert.p12" \
-        -pass passme \
-        -in "test.ex_" -out "test_052.ex_"
-    verify_signature "$?" "052" "ex_" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    number="$test_nr$format_nr"
+    test_name="Sign a $filetype$desc file with a certificate and a key stored in a PKCS#12 container"
+    printf "\n%03d. %s\n" "$number" "$test_name"
 
-# MSI file
-test_name="053. Sign a MSI file with a certificate and key stored in a PKCS#12 container"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -pkcs12 "${script_path}/../certs/cert.p12" \
-        -pass passme \
-        -in "sample.msi" -out "test_053.msi"
-    verify_signature "$?" "053" "msi" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -st "1556668800" \
+      -pkcs12 "${script_path}/../certs/cert.p12" \
+      -pass passme \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    result=$?
 
-# CAT file
-test_name="054. Sign a CAT file with a certificate and key stored in a PKCS#12 container"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -pkcs12 "${script_path}/../certs/cert.p12" \
-        -pass passme \
-        -in "good.cat" -out "test_054.cat"
-    verify_signature "$?" "054" "cat" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "osslsigncode" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "sha256sum" "osslsigncode" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/16_sign_comm b/tests/recipes/16_sign_comm
--- a/tests/recipes/16_sign_comm
+++ b/tests/recipes/16_sign_comm
@@ -1,78 +1,58 @@
 #!/bin/sh
-# Sign a PE/CAB/MSI file with the commercial purpose set for SPC_STATEMENT_TYPE_OBJID
+# Sign a file with Microsoft Commercial Code Signing purpose set for SPC_STATEMENT_TYPE_OBJID
 # object ID numbers (OIDs) "1.3.6.1.4.1.311.2.1.11"
-# changes default Individual Code Signing: "0x30, 0x0c, x06, 0x0a, 0x2b, 0x06, 0x01, 0x04, 0x01, 0x82, 0x37, 0x02, 0x01, 0x15"
-# sets Commercial Code Signing: "0x30, 0x0c, x06, 0x0a, 0x2b, 0x06, 0x01, 0x04, 0x01, 0x82, 0x37, 0x02, 0x01, 0x16"
+# changes default Microsoft Individual Code Signing:
+# "0x30, 0x0c, x06, 0x0a, 0x2b, 0x06, 0x01, 0x04, 0x01, 0x82, 0x37, 0x02, 0x01, 0x15"
+# sets Microsoft Commercial Code Signing:
+# "0x30, 0x0c, x06, 0x0a, 0x2b, 0x06, 0x01, 0x04, 0x01, 0x82, 0x37, 0x02, 0x01, 0x16"
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=16
 
-# PE file
-test_name="161. Sign a PE file with the common purpose set"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -comm \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.exe" -out "test_161.exe"
-    verify_signature "$?" "161" "exe" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "HEX" "300c060a2b060104018237020116" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") filetype=CAT; format_nr=1 ;;
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
 
-# CAB file
-test_name="162. Sign a CAB file with the common purpose set"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -comm \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.ex_" -out "test_162.ex_"
-    verify_signature "$?" "162" "ex_" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "HEX" "300c060a2b060104018237020116" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    number="$test_nr$format_nr"
+    test_name="Sign a $filetype$desc file with the common purpose set"
+    printf "\n%03d. %s\n" "$number" "$test_name"
 
-# MSI file
-test_name="163. Sign a MSI file with the common purpose set"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -comm \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "sample.msi" -out "test_163.msi"
-    verify_signature "$?" "163" "msi" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "HEX" "300c060a2b060104018237020116" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -st "1556668800" \
+      -comm \
+      -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    result=$?
 
-# CAT file
-test_name="164. Sign a CAT file with the common purpose set"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -comm \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "good.cat" -out "test_164.cat"
-    verify_signature "$?" "164" "cat" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "HEX" "300c060a2b060104018237020116" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "UNUSED_PATTERN" "Microsoft Commercial Code Signing" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/26_extract_signature_pem b/tests/recipes/26_extract_signature_pem
--- a/tests/recipes/26_extract_signature_pem
+++ b/tests/recipes/26_extract_signature_pem
@@ -1,64 +1,55 @@
 #!/bin/sh
-# Extract the signature in the PEM format from the PE/CAB/MSI file.
+# Extract the signature in the PEM format.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=26
 
-# PE file
-test_name="261. Extract the PEM signature from the PE file"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") continue;; # Unsupported command
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
+
+    number="$test_nr$format_nr"
+    test_name="Extract the PEM signature from the $filetype$desc file"
+    printf "\n%03d. %s\n" "$number" "$test_name"
+
     ../../osslsigncode sign -h sha512 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.exe" -out "test_261.exe" && \
-    ../../osslsigncode extract-signature -pem \
-        -in "test_261.exe" -out "sign_pe.pem"
-    verify_signature "$?" "261" "exe" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "SHA512" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -st "1556668800" \
+      -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    ../../osslsigncode extract-signature \
+      -pem \
+      -in "test_$number.$ext" -out "sign_$format_nr.pem"
+    result=$?
 
-# CAB file
-test_name="262. Extract the PEM signature from the CAB file"
-printf "\n%s\n" "$test_name"
-if [ -s "test.ex_" ]
-  then
-    ../../osslsigncode sign -h sha512 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.ex_" -out "test_262.ex_" && \
-    ../../osslsigncode extract-signature -pem \
-        -in "test_262.ex_" -out "sign_cab.pem"
-    verify_signature "$?" "262" "ex_" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "SHA512" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
-
-# MSI file
-test_name="263. Extract the PEM signature from the MSI file"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
-    ../../osslsigncode sign -h sha512 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "sample.msi" -out "test_263.msi" && \
-    ../../osslsigncode extract-signature -pem \
-        -in "test_263.msi" -out "sign_msi.pem"
-    verify_signature "$?" "263" "msi" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "SHA512" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
-
-# CAT file
-# Unsupported command
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "sha256sum" "SHA512" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/31_attach_signature_der b/tests/recipes/31_attach_signature_der
--- a/tests/recipes/31_attach_signature_der
+++ b/tests/recipes/31_attach_signature_der
@@ -1,61 +1,57 @@
 #!/bin/sh
-# Attach the DER signature to the PE/CAB/MSI file.
+# Attach the DER signature to the file.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=31
 
-# PE file
-test_name="311. Attach the DER signature to the PE file"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") continue;; # Unsupported command
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
+
+    number="$test_nr$format_nr"
+    test_name="Attach the DER signature to the $filetype$desc file"
+    printf "\n%03d. %s\n" "$number" "$test_name"
+
     ../../osslsigncode attach-signature \
-        -sigin "sign_pe.der" \
-        -CAfile "${script_path}/../certs/CACert.pem" \
-        -CRLfile "${script_path}/../certs/CACertCRL.pem" \
-        -in "test.exe" -out "test_311.exe"
-    verify_signature "$?" "311" "exe" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "SHA512" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -sigin "sign_$format_nr.der" \
+      -CAfile "${script_path}/../certs/CACert.pem" \
+      -CRLfile "${script_path}/../certs/CACertCRL.pem" \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    result=$?
 
-# CAB file
-test_name="312. Attach the DER signature to the CAB file"
-printf "\n%s\n" "$test_name"
-if [ -s "test.ex_" ]
-  then
-    ../../osslsigncode attach-signature \
-        -sigin "sign_cab.der" \
-        -CAfile "${script_path}/../certs/CACert.pem" \
-        -CRLfile "${script_path}/../certs/CACertCRL.pem" \
-        -in "test.ex_" -out "test_312.ex_"
-    verify_signature "$?" "312" "ex_" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "SHA512" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    if test "$result" -ne 0; then
+      cp "sign_$format_nr.der" "sign_$number.der"
+    fi
 
-# MSI file
-test_name="313. Attach the DER signature to the MSI file"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
-    ../../osslsigncode attach-signature \
-        -sigin "sign_msi.der" \
-        -CAfile "${script_path}/../certs/CACert.pem" \
-        -CRLfile "${script_path}/../certs/CACertCRL.pem" \
-        -in "sample.msi" -out "test_313.msi"
-    verify_signature "$?" "313" "msi" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "SHA512" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
-
-# CAT file
-# Unsupported command
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "sha256sum" "SHA512" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/33_attach_signed b/tests/recipes/33_attach_signed
--- a/tests/recipes/33_attach_signed
+++ b/tests/recipes/33_attach_signed
@@ -1,72 +1,57 @@
 #!/bin/sh
-# Attach the signature to the signed PE/CAB/MSI file.
+# Attach the signature to the signed file.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=33
 
-# PE file
-test_name="331. Attach the signature to the signed PE file"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") continue;; # Unsupported command
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
+
+    number="$test_nr$format_nr"
+    test_name="Attach the PEM signature to the signed $filetype$desc file"
+    printf "\n%03d. %s\n" "$number" "$test_name"
+
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.exe" -out "test_331_signed.exe"
+      -st "1556668800" \
+      -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
+      -in "notsigned/$name" -out "signed_$number.$ext"
     ../../osslsigncode attach-signature \
-        -sigin "sign_pe.pem" \
-        -CAfile "${script_path}/../certs/CACert.pem" \
-        -CRLfile "${script_path}/../certs/CACertCRL.pem" \
-        -in "test_331_signed.exe" -out "test_331.exe"
-    verify_signature "$?" "331" "exe" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "SHA512" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -sigin "sign_$format_nr.pem" \
+      -CAfile "${script_path}/../certs/CACert.pem" \
+      -CRLfile "${script_path}/../certs/CACertCRL.pem" \
+      -in "signed_$number.$ext" -out "test_$number.$ext"
+    result=$?
 
-# CAB file
-test_name="332. Attach the signature to the signed CAB file"
-printf "\n%s\n" "$test_name"
-if [ -s "test.ex_" ]
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.ex_" -out "test_332_signed.ex_"
-    ../../osslsigncode attach-signature \
-        -sigin "sign_cab.pem" \
-        -CAfile "${script_path}/../certs/CACert.pem" \
-        -CRLfile "${script_path}/../certs/CACertCRL.pem" \
-        -in "test_332_signed.ex_" -out "test_332.ex_"
-    verify_signature "$?" "332" "ex_" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "SHA512" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
-
-# MSI file
-test_name="333. Attach the signature to the signed MSI file"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "sample.msi" -out "test_333_signed.msi"
-    ../../osslsigncode attach-signature -sigin "sign_msi.pem" \
-        -CAfile "${script_path}/../certs/CACert.pem" \
-        -CRLfile "${script_path}/../certs/CACertCRL.pem" \
-        -in "test_333_signed.msi" -out "test_333.msi"
-    verify_signature "$?" "333" "msi" "success" "@2019-09-01 12:00:00" \
-	"sha256sum" "ASCII" "SHA512" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
-
-# CAT file
-# Unsupported command
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+        "sha256sum" "SHA512" "UNUSED_PATTERN"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
diff --git a/tests/recipes/37_add_signature_timestamp b/tests/recipes/37_add_signature_timestamp
--- a/tests/recipes/37_add_signature_timestamp
+++ b/tests/recipes/37_add_signature_timestamp
@@ -1,92 +1,64 @@
 #!/bin/sh
-# Add an authenticode timestamp to the PE/CAB/MSI file.
+# Add an authenticode timestamp to the signed file.
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=37
 
-# PE file
-test_name="371. Add an authenticode timestamp to the PE file"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe" && ! grep -q "no libcurl available" "results.log"
-  then
-    ../../osslsigncode sign -h sha256 \
+if ! grep -q "no libcurl available" "results.log"; then
+  for file in ${script_path}/../logs/notsigned/*.*
+    do
+      name="${file##*/}"
+      ext="${file##*.}"
+      desc=""
+      case $ext in
+        "cat") filetype=CAT; format_nr=1 ;;
+        "msi") filetype=MSI; format_nr=2 ;;
+        "ex_") filetype=CAB; format_nr=3 ;;
+        "exe") filetype=PE; format_nr=4 ;;
+        "ps1")
+          filetype=TXT
+          if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+            format_nr=5
+            desc=" UTF-16LE(BOM)"
+          elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+            format_nr=6
+            desc=" UTF-8(BOM)"
+        else
+            format_nr=7
+            desc=" UTF-8"
+          fi ;;
+      esac
+
+      number="$test_nr$format_nr"
+      test_name="Add an authenticode timestamp to the $filetype$desc signed file"
+      printf "\n%03d. %s\n" "$number" "$test_name"
+
+      ../../osslsigncode sign -h sha256 \
         -st "1556668800" \
         -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.exe" -out "test_371_signed.exe" && \
-    ../../osslsigncode add \
+        -in "notsigned/$name" -out "signed_$number.$ext"
+      ../../osslsigncode add \
         -t http://time.certum.pl/ \
         -t http://timestamp.digicert.com/ \
         -verbose \
-        -in "test_371_signed.exe" -out "test_371.exe"
-    verify_signature "$?" "371" "exe" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "Timestamp Server Signature" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+        -in "signed_$number.$ext" -out "test_$number.$ext"
+      result=$?
 
-# CAB file
-test_name="372. Add an authenticode timestamp to the CAB file"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_" && ! grep -q "no libcurl available" "results.log"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "test.ex_" -out "test_372_signed.ex_" && \
-    ../../osslsigncode add \
-        -t http://time.certum.pl/ \
-        -t http://timestamp.digicert.com/ \
-        -verbose \
-        -in "test_372_signed.ex_" -out "test_372.ex_"
-    verify_signature "$?" "372" "ex_" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "Timestamp Server Signature" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
+      if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+        printf "%s\n" "Compare file prefix failed"
+        test_result "1" "$number" "$test_name"
+      else
+        verify_signature "$result" "$number" "$ext" "success" "@2019-09-01 12:00:00" \
+          "UNUSED_PATTERN" "Timestamp Server Signature" "UNUSED_PATTERN"
+        test_result "$?" "$number" "$test_name"
+      fi
+    done
   else
-    printf "Test skipped\n"
+    format_nr=0
+    number="$test_nr$format_nr"
+    test_name="Add an authenticode timestamp to the signed file"
+    printf "\n%03d. %s\nTest skipped\n" "$number" "$test_name"
   fi
-
-# MSI file
-test_name="373. Add an authenticode timestamp to the MSI file"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi" && ! grep -q "no libcurl available" "results.log"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "sample.msi" -out "test_373_signed.msi" && \
-    ../../osslsigncode add \
-        -t http://time.certum.pl/ \
-        -t http://timestamp.digicert.com/ \
-        -verbose \
-        -in "test_373_signed.msi" -out "test_373.msi"
-    verify_signature "$?" "373" "msi" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "Timestamp Server Signature" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
-
-# CAT file
-test_name="374. Add an authenticode timestamp to the CAT file"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat" && ! grep -q "no libcurl available" "results.log"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.pem" \
-        -in "good.cat" -out "test_374_signed.cat" && \
-    ../../osslsigncode add \
-        -t http://time.certum.pl/ \
-        -t http://timestamp.digicert.com/ \
-        -verbose \
-        -in "test_374_signed.cat" -out "test_374.cat"
-    verify_signature "$?" "374" "cat" "success" "@2019-09-01 12:00:00" \
-	"UNUSED_PATTERN" "ASCII" "Timestamp Server Signature" "UNUSED_PATTERN"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
-
 
 exit 0
diff --git a/tests/recipes/40_verify_leaf_hash b/tests/recipes/40_verify_leaf_hash
--- a/tests/recipes/40_verify_leaf_hash
+++ b/tests/recipes/40_verify_leaf_hash
@@ -1,67 +1,51 @@
 #!/bin/sh
-# Compare the leaf certificate hash against specified SHA256 message digest for the PE/CAB/MSI file
+# Compare the leaf certificate hash against specified SHA256 message digest for the file
 
 . $(dirname $0)/../test_library
 script_path=$(pwd)
+test_nr=40
 
-# PE file
-test_name="401. Compare the leaf certificate hash against specified SHA256 message digest for the PE file"
-printf "\n%s\n" "$test_name"
-if test -s "test.exe"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
-        -in "test.exe" -out "test_401.exe"
-    verify_leaf_hash "$?" "401" "exe" "@2019-05-01 00:00:00"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+for file in ${script_path}/../logs/notsigned/*.*
+  do
+    name="${file##*/}"
+    ext="${file##*.}"
+    desc=""
+    case $ext in
+      "cat") filetype=CAT; format_nr=1 ;;
+      "msi") filetype=MSI; format_nr=2 ;;
+      "ex_") filetype=CAB; format_nr=3 ;;
+      "exe") filetype=PE; format_nr=4 ;;
+      "ps1")
+        filetype=TXT
+        if xxd -p -l 2 "notsigned/$name" | grep -q "fffe"; then
+          format_nr=5
+          desc=" UTF-16LE(BOM)"
+        elif xxd -p -l 3 "notsigned/$name" | grep -q "efbbbf"; then
+          format_nr=6
+          desc=" UTF-8(BOM)"
+        else
+          format_nr=7
+          desc=" UTF-8"
+        fi ;;
+    esac
 
-# CAB file
-test_name="402. Compare the leaf certificate hash against specified SHA256 message digest for the CAB file"
-printf "\n%s\n" "$test_name"
-if test -s "test.ex_"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
-        -in "test.ex_" -out "test_402.ex_"
-    verify_leaf_hash "$?" "402" "ex_" "@2019-05-01 00:00:00"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    number="$test_nr$format_nr"
+    test_name="Compare the leaf hash against SHA256 message digest for the $filetype$desc file"
+    printf "\n%03d. %s\n" "$number" "$test_name"
 
-# MSI file
-test_name="403. Compare the leaf certificate hash against specified SHA256 message digest for the MSI file"
-printf "\n%s\n" "$test_name"
-if test -s "sample.msi"
-  then
     ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
-        -in "sample.msi" -out "test_403.msi"
-    verify_leaf_hash "$?" "403" "msi" "@2019-05-01 00:00:00"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+      -st "1556668800" \
+      -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
+      -in "notsigned/$name" -out "test_$number.$ext"
+    result=$?
 
-# CAT file
-test_name="404. Compare the leaf certificate hash against specified SHA256 message digest for the CAT file"
-printf "\n%s\n" "$test_name"
-if test -s "good.cat"
-  then
-    ../../osslsigncode sign -h sha256 \
-        -st "1556668800" \
-        -certs "${script_path}/../certs/cert.pem" -key "${script_path}/../certs/key.der" \
-        -in "good.cat" -out "test_404.cat"
-    verify_leaf_hash "$?" "404" "cat" "@2019-05-01 00:00:00"
-    test_result "$?" "$test_name"
-  else
-    printf "Test skipped\n"
-  fi
+    if test "$filetype" = "TXT" && ! cmp -l -n 3 "notsigned/$name" "test_$number.$ext"; then
+      printf "%s\n" "Compare file prefix failed"
+      test_result "1" "$number" "$test_name"
+    else
+      verify_leaf_hash "$result" "$number" "$ext" "@2019-05-01 00:00:00"
+      test_result "$?" "$number" "$test_name"
+    fi
+  done
 
 exit 0
